### ISSUE TITLE
Use HTTPS & Fetch from purism infra

### ISSUE THREAD

**Issue by emanuelb** [purism/purism-librem-coreboot-updater#9]
The coreboot downloaded via HTTP from domain that accessible via DynamicDNS
> COREBOOT_BASE_URL='http://kakaroto.homelinux.net/purism/coreboot_base_bios.rom.bz2'

fix:
1. use HTTPS instead of HTTP.
2. host the file on Purism infrastructure

See also my comment regarding issue "https://github.com/purism/purism-librem-coreboot-updater/issues/3" [build coreboot during packaging]
https://github.com/purism/purism-librem-coreboot-updater/issues/3#issuecomment-308332251

**Comment by kakaroto** [comment]
This was during development, the image will be included in the deb directory, so no https/http is needed once #3 is fixed.
